
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Doctor
{

using System;
    using System.Collections.Generic;
    
public partial class Autoris
{

    public int ID { get; set; }

    public string Login { get; set; }

    public byte[] Pass { get; set; }

    public string First_Name { get; set; }

    public string Name { get; set; }

    public string Otchestvo { get; set; }

}

}
