

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Doctor
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Heal1 : DbContext
{
    public Heal1()
        : base("name=Heal1")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Autoris> Autoris { get; set; }

    public virtual DbSet<OutputInfo> OutputInfo { get; set; }

}

}

